### ISSUE TITLE
Please contact me about this repo contents

### ISSUE THREAD

**Issue by ragdelaed** [amishaaggarwal/BudgetApprovalSystem#14]
Hello, my name is Eddy, I work at BMS, please contact me when you get this regarding this repo contents, specifically, 

**https://github.com/amishaaggarwal/BudgetApprovalSystem/blob/e59eab8e6b19422317e70865c6f8f2732ffab272/backend/bms/db.sqlite3**

I am asking if you would remove this page please. Thanks.

Mobile: +1.678.630.6112
Email:edgar.deal@bms.com

**Comment by amishaaggarwal** [comment]
removed the file
